/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { customInstance } from './axios-instance';
export interface Course {
  course_id?: number | null;
  instructor_id: number;
  title: string;
  course_number: string;
  credits: number;
}

export interface CreateCourseRequest {
  instructor_id: number;
  title: string;
  course_number: string;
  credits: number;
}

export interface CreateCourseResponse {
  course_id: number;
}

export interface CreateInstructorRequest {
  first_name: string;
  last_name: string;
  email: string;
}

export interface CreateInstructorResponse {
  id: number;
}

export interface CreateStudentRequest {
  first_name: string;
  last_name: string;
  email: string;
}

export interface CreateStudentResponse {
  student_id: number;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface Instructor {
  id?: number | null;
  first_name: string;
  last_name: string;
  email: string;
}

export interface Student {
  student_id?: number | null;
  first_name: string;
  last_name: string;
  email: string;
}

export interface UpdateCourseRequest {
  instructor_id?: number | null;
  title?: string | null;
  course_number?: string | null;
  credits?: number | null;
}

export interface UpdateInstructorRequest {
  first_name?: string | null;
  last_name?: string | null;
  email?: string | null;
}

export interface UpdateStudentRequest {
  first_name?: string | null;
  last_name?: string | null;
  email?: string | null;
}

export type GetStudentCoursesStudentsStudentIdCoursesGet200 = {[key: string]: string};

export type AddStudentToCourseStudentsStudentIdPostParams = {
course_id: number;
};

export type GetInstructorCoursesInstructorsIdCoursesGet200 = {[key: string]: string};

export const getFastAPI = () => {
/**
 * @summary Get Students
 */
const getStudentsStudentsGet = (

 ) => {
      return customInstance<Student[]>(
      {url: `/students`, method: 'GET'
    },
      );
    }

/**
 * @summary Create Student
 */
const createStudentStudentsPost = (
    createStudentRequest: CreateStudentRequest,
 ) => {
      return customInstance<CreateStudentResponse>(
      {url: `/students`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createStudentRequest
    },
      );
    }

/**
 * @summary Get Student Courses
 */
const getStudentCoursesStudentsStudentIdCoursesGet = (
    studentId: number,
 ) => {
      return customInstance<GetStudentCoursesStudentsStudentIdCoursesGet200>(
      {url: `/students/${studentId}/courses`, method: 'GET'
    },
      );
    }

/**
 * @summary Add Student To Course
 */
const addStudentToCourseStudentsStudentIdPost = (
    studentId: number,
    params: AddStudentToCourseStudentsStudentIdPostParams,
 ) => {
      return customInstance<unknown>(
      {url: `/students/${studentId}`, method: 'POST',
        params
    },
      );
    }

/**
 * @summary Update Student
 */
const updateStudentStudentsStudentIdPatch = (
    studentId: number,
    updateStudentRequest: UpdateStudentRequest,
 ) => {
      return customInstance<void>(
      {url: `/students/${studentId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateStudentRequest
    },
      );
    }

/**
 * @summary Delete Student
 */
const deleteStudentStudentsStudentIdDelete = (
    studentId: number,
 ) => {
      return customInstance<void>(
      {url: `/students/${studentId}`, method: 'DELETE'
    },
      );
    }

/**
 * @summary Get Instructors
 */
const getInstructorsInstructorsGet = (

 ) => {
      return customInstance<Instructor[]>(
      {url: `/instructors`, method: 'GET'
    },
      );
    }

/**
 * @summary Create Instructor
 */
const createInstructorInstructorsPost = (
    createInstructorRequest: CreateInstructorRequest,
 ) => {
      return customInstance<CreateInstructorResponse>(
      {url: `/instructors`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createInstructorRequest
    },
      );
    }

/**
 * {
 *     "CS 1400": "Fundamentals of Programming",
 *     "CS 1410": "Object-oriented Programming 2",
 *     "CS 2420": "Data Structures and Algorithms"
 * }
 * @summary Get Instructor Courses
 */
const getInstructorCoursesInstructorsIdCoursesGet = (
    id: number,
 ) => {
      return customInstance<GetInstructorCoursesInstructorsIdCoursesGet200>(
      {url: `/instructors/${id}/courses`, method: 'GET'
    },
      );
    }

/**
 * @summary Get Number Of Course
 */
const getNumberOfCourseInstructorsIdNumCoursesGet = (
    id: number,
 ) => {
      return customInstance<number>(
      {url: `/instructors/${id}/num-courses`, method: 'GET'
    },
      );
    }

/**
 * @summary Update Instructor
 */
const updateInstructorInstructorsIdPatch = (
    id: number,
    updateInstructorRequest: UpdateInstructorRequest,
 ) => {
      return customInstance<void>(
      {url: `/instructors/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateInstructorRequest
    },
      );
    }

/**
 * @summary Delete Instructor
 */
const deleteInstructorInstructorsIdDelete = (
    id: number,
 ) => {
      return customInstance<void>(
      {url: `/instructors/${id}`, method: 'DELETE'
    },
      );
    }

/**
 * @summary Get Courses
 */
const getCoursesCoursesGet = (

 ) => {
      return customInstance<Course[]>(
      {url: `/courses`, method: 'GET'
    },
      );
    }

/**
 * @summary Create Course
 */
const createCourseCoursesPost = (
    createCourseRequest: CreateCourseRequest,
 ) => {
      return customInstance<CreateCourseResponse>(
      {url: `/courses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCourseRequest
    },
      );
    }

/**
 * @summary Update Course
 */
const updateCourseCoursesIdPatch = (
    id: number,
    updateCourseRequest: UpdateCourseRequest,
 ) => {
      return customInstance<void>(
      {url: `/courses/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateCourseRequest
    },
      );
    }

/**
 * @summary Delete Course
 */
const deleteCourseCourseCourseIdDelete = (
    courseId: number,
 ) => {
      return customInstance<void>(
      {url: `/course/${courseId}`, method: 'DELETE'
    },
      );
    }

return {getStudentsStudentsGet,createStudentStudentsPost,getStudentCoursesStudentsStudentIdCoursesGet,addStudentToCourseStudentsStudentIdPost,updateStudentStudentsStudentIdPatch,deleteStudentStudentsStudentIdDelete,getInstructorsInstructorsGet,createInstructorInstructorsPost,getInstructorCoursesInstructorsIdCoursesGet,getNumberOfCourseInstructorsIdNumCoursesGet,updateInstructorInstructorsIdPatch,deleteInstructorInstructorsIdDelete,getCoursesCoursesGet,createCourseCoursesPost,updateCourseCoursesIdPatch,deleteCourseCourseCourseIdDelete}};
export type GetStudentsStudentsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['getStudentsStudentsGet']>>>
export type CreateStudentStudentsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['createStudentStudentsPost']>>>
export type GetStudentCoursesStudentsStudentIdCoursesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['getStudentCoursesStudentsStudentIdCoursesGet']>>>
export type AddStudentToCourseStudentsStudentIdPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['addStudentToCourseStudentsStudentIdPost']>>>
export type UpdateStudentStudentsStudentIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['updateStudentStudentsStudentIdPatch']>>>
export type DeleteStudentStudentsStudentIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['deleteStudentStudentsStudentIdDelete']>>>
export type GetInstructorsInstructorsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['getInstructorsInstructorsGet']>>>
export type CreateInstructorInstructorsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['createInstructorInstructorsPost']>>>
export type GetInstructorCoursesInstructorsIdCoursesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['getInstructorCoursesInstructorsIdCoursesGet']>>>
export type GetNumberOfCourseInstructorsIdNumCoursesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['getNumberOfCourseInstructorsIdNumCoursesGet']>>>
export type UpdateInstructorInstructorsIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['updateInstructorInstructorsIdPatch']>>>
export type DeleteInstructorInstructorsIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['deleteInstructorInstructorsIdDelete']>>>
export type GetCoursesCoursesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['getCoursesCoursesGet']>>>
export type CreateCourseCoursesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['createCourseCoursesPost']>>>
export type UpdateCourseCoursesIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['updateCourseCoursesIdPatch']>>>
export type DeleteCourseCourseCourseIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['deleteCourseCourseCourseIdDelete']>>>
